name: CI/CD

on:
  create:
    branches: [ "release/**" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      if:  ${{ !startsWith(github.ref, 'refs/heads/release') }}
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: mad9000/actions-find-and-replace-string@5
      id: version
      with:
        source: ${{ github.ref }}
        find: 'refs/heads/release/'
        replace: ''
    - name: Publish
      if:  ${{ startsWith(github.ref, 'refs/heads/release') }}
      run: | 
        dotnet build --no-restore /p:PackageVersion=${{ steps.version.outputs.value }}
        nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
      
