# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  create:
    branches: [ "release/**" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - uses: tj-actions/branch-names@v8
      id: branch-names
      with:
        # The prefix that should be 
        # stripped from the tag e.g 
        # `v` -> with a tag 
        # `v0.0.1` -> returns `0.0.1` 
        # Type: string
        strip_tag_prefix: 'release/'
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:PackageVersion=${{ steps.branch-names.outputs.current_branch }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
      
